
---

# -------------------------------------------------------------------
epic-games-plr:            # Epic Games edge regression dataset
# -------------------------------------------------------------------
    random_state:     42          # Random seed
    split:                        # Data split
        test_prop:    0.2           # Test set data ratio
        valid_prop:   0.1           # Validation set data ratio
    model:                        # Model parameters
        dropout:      0.1           # Dropout ratio
        input_dim:    573            # Node feature dimension
        hidden_dim:   128            # Hidden layer output feature dimension
        output_dim:    512           # Edge feature dimension
        num_heads: 4              # Number of attention heads
        num_layers: 2            # Number of transformer encoder layers
        dim_feedforward: 2       # FFN layer hidden dimension
    hyper:                        # Training hyperparameters
        lr:           0.001         # Optimizer initial learning rate
        epochs:       10            # Number of training epochs
        patience:     100            # Early stopping patience
        weight_decay: 0.0005        # Optimizer weight decay
    sampling:
        train_times_per_epoch: 10


# -------------------------------------------------------------------
air-traffic-2019-rlr:            # Air Traffic 2019 edge regression dataset
# -------------------------------------------------------------------
    random_state:     42          # Random seed
    split:                        # Data split
        test_prop:    0.2           # Test set data ratio
        valid_prop:   0.1           # Validation set data ratio
    model:                        # Model parameters
        dropout:      0.1           # Dropout ratio
        input_dim:    128            # Node feature dimension
        hidden_dim:   128            # Hidden layer output feature dimension
        output_dim:    20           # Edge feature dimension
        num_heads: 4              # Number of attention heads
        num_layers: 2            # Number of transformer encoder layers
        dim_feedforward: 2       # FFN layer hidden dimension
    hyper:                        # Training hyperparameters
        lr:           0.001         # Optimizer initial learning rate
        epochs:       1000            # Number of training epochs
        patience:     100            # Early stopping patience
        weight_decay: 0.0005        # Optimizer weight decay
    sampling:
        train_times_per_epoch: 10


# -------------------------------------------------------------------
air-traffic-2015-rlr:            # Air Traffic 2015 edge regression dataset
# -------------------------------------------------------------------
    random_state:     42          # Random seed
    split:                        # Data split
        test_prop:    0.2           # Test set data ratio
        valid_prop:   0.1           # Validation set data ratio
    model:                        # Model parameters
        dropout:      0.1           # Dropout ratio
        input_dim:    128            # Node feature dimension
        hidden_dim:   128            # Hidden layer output feature dimension
        output_dim:    20           # Edge feature dimension
        num_heads: 4              # Number of attention heads
        num_layers: 2            # Number of transformer encoder layers
        dim_feedforward: 2       # FFN layer hidden dimension
    hyper:                        # Training hyperparameters
        lr:           0.001         # Optimizer initial learning rate
        epochs:       1000            # Number of training epochs
        patience:     100            # Early stopping patience
        weight_decay: 0.0005        # Optimizer weight decay
    sampling:
        train_times_per_epoch: 10
